[app]
cheatsheet = "F1"
me = "m"
quit = "q"

[cursor]
bottom_of_window = "L"
middle_of_window = "M"
top_of_window = "H"

[general]
bottom = "G"
down = "j"
left = "h"
page_down = "d"
page_up = "u"
right = "l"
top = "g"
up = "k"

[status]
compose = "^N"
conversation = "c"
destroy = "D"
like = "F"
open_link = "o"
quote = "Q"
reply = "r"
retweet = "R"
user = "U"

[tab]
1st = "1"
2nd = "2"
3rd = "3"
4th = "4"
5th = "5"
6th = "6"
7th = "7"
8th = "8"
9th = "9"
close = "w"
find_next = "n"
find_previous = "N"
last = "0"
new = "^T"
reload = "^R"
search_down = "/"
search_up = "?"
