#!/bin/bash
#
# Adds a blank space to the dock

if [ $(uname) == 'Darwin' ]; then
	defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="spacer-tile";}'
	killall Dock
else
	echo 'AddDockSpace is only applicable on OS X'
fi
